title: "The Disco Chap"
tagline: "A blog about disco"
email: hello@discochap.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about all things disco, from the 1970s to the present day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      sidebar: true
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - assets/src

#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
